name: QA Automation Pipeline (Smoke + Regression)

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

  schedule:
    - cron: "0 */12 * * *"

jobs:
  smoke-tests:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/setup.yml
    with:
      test-type: smoke

  nightly-regression:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/setup.yml
    with:
      test-type: regression